server:
  port: ${SERVER_PORT}

spring:
  application:
    name: pizzeria

  datasource:
    url: jdbc:${DATABASE}://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    show-sql:  ${SHOW_SQL}
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL}

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION}
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION}


